export const ADD_USER_REGISTER_REQUEST = "USER_REGISTER/ADD_USER_REGISTER_REQUEST";
export const ADD_USER_REGISTER_SUCCESS = "USER_REGISTER/ADD_USER_REGISTER_SUCCESS";
export const ADD_USER_REGISTER_FAIL = "USER_REGISTER/ADD_USER_REGISTER_FAIL";

