// Định nghĩa các action types

export const UPDATE_GYM_CLB_LIST_PENDING = "clb/UPDATE_GYM_CLB_LIST_PENDING";
export const EDIT_GYM_CLB_LIST_PENDING = "clb/EDIT_GYM_CLB_LIST_PENDING";
export const DELETE_GYM_CLB_LIST_PENDING = "clb/DELETE_GYM_CLB_LIST_PENDING ";
