// Định nghĩa các action types

export const UPDATE_GYM_KHOATAP_LIST_PENDING = "KHOATAP/UPDATE_GYM_KHOATAP_LIST_PENDING";
export const EDIT_GYM_KHOATAP_LIST_PENDING = "KHOATAP/EDIT_GYM_KHOATAP_LIST_PENDING";
export const DELETE_GYM_KHOATAP_LIST_PENDING = "KHOATAP/DELETE_GYM_KHOATAP_LIST_PENDING ";
