// Định nghĩa các action types

export const UPDATE_GYM_TINTUC_LIST_PENDING = "TINTUC/UPDATE_GYM_TINTUC_LIST_PENDING";
export const EDIT_GYM_TINTUC_LIST_PENDING = "TINTUC/EDIT_GYM_TINTUC_LIST_PENDING";
export const DELETE_GYM_TINTUC_LIST_PENDING = "TINTUC/DELETE_GYM_TINTUC_LIST_PENDING ";
