// Định nghĩa các action types

export const UPDATE_GYM_HOCVIEN_LIST_PENDING = "HOCVIEN/UPDATE_GYM_HOCVIEN_LIST_PENDING";
export const EDIT_GYM_HOCVIEN_LIST_PENDING = "HOCVIEN/EDIT_GYM_HOCVIEN_LIST_PENDING";
export const DELETE_GYM_HOCVIEN_LIST_PENDING = "HOCVIEN/DELETE_GYM_HOCVIEN_LIST_PENDING ";
