// Định nghĩa các action types

export const UPDATE_GYM_HOADON_LIST_PENDING = "HOADON/UPDATE_GYM_HOADON_LIST_PENDING";
export const EDIT_GYM_HOADON_LIST_PENDING = "HOADON/EDIT_GYM_HOADON_LIST_PENDING";
export const DELETE_GYM_HOADON_LIST_PENDING = "HOADON/DELETE_GYM_HOADON_LIST_PENDING ";
